version: "3"

services:
  cron:
    depends_on:
      - backend
      - mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    image: amigcamel/backup:latest
    networks:
      - welfare
    volumes:
      - /tmp/backup:/backup
  frontend:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    image: amigcamel/fe:latest
    networks:
      - welfare
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
  backend:
    depends_on:
      - mongo
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - backend.env
    image: amigcamel/be:latest
    networks:
      - welfare
  mongo:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    image: mongo:4.2.7
    networks:
      - welfare
    volumes:
      - mongo-data:/data/db
  redis:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    image: redis:6.0.4-alpine3.11
    networks:
      - welfare


networks:
  welfare:

volumes:
  mongo-data:
