version: "3"

services:
  backend:
    command: >
      -c "
      python -c 'import json as j, pymongo as p; p.MongoClient(\"mongo\").afternoontea.demo_1.insert_one(j.load(open(\"/tmp/service/mock2.json\")))' &&
      uwsgi uwsgi.ini
      "
    depends_on:
      - mongo
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    entrypoint: /bin/sh
    environment:
      - FLASK_ENV=development
    image: be:latest
    networks:
      - welfare
    ports:
      - 5000:5000
    volumes:
      - ./backend:/backend 
      - ./frontend/src/app/service:/tmp/service
  mongo:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    image: mongo:4.2.7
    networks:
      - welfare
    ports:
      - 27017:27017
  redis:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    image: redis:6.0.4-alpine3.11
    networks:
      - welfare
    ports:
      - 6379:6379


networks:
  welfare:

volumes:
  db-data:
